management:
  server:
    port: 9001
  endpoints:
    web:
      #修改访问路径
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      #显示健康具体信息    默认不会显示详细信息
      show-details: always

server:
  port: 8081
